
-- Crear base de datos.
CREATE DATABASE CHOLITOS_GYM;

-- Poner en uso la base de datos.
USE CHOLITOS_GYM;

/*
	-- Crear login para usuario de base de datos.
	CREATE LOGIN CHOLGYM WITH PASSWORD = 'Chol!tos2024';
	-- Asignar login a usuario.
	CREATE USER CHOLGYM FOR LOGIN CHOLGYM;
*/

-- Tabla para cliente.
CREATE TABLE CHOLITOS_GYM_CLIENTE(
	CLIENTE					INT				NOT NULL IDENTITY(1,1),
	CODIGO_GENERACION		VARCHAR(10)		NOT NULL,
	PRIMER_NOMBRE			VARCHAR(30)		NOT NULL,
	SEGUNDO_NOMBRE			VARCHAR(30),
	PRIMER_APELLIDO			VARCHAR(30)		NOT NULL,
	SEGUNDO_APELLIDO		VARCHAR(30),
	APELLIDO_CASADA			VARCHAR(30),
	FECHA_PAGO				DATE			NOT NULL,
	FECHA_INICIO			DATE			NOT NULL,
	FECHA_FIN	DATE			NOT NULL,
	FIRMA					CHAR(1),
	TIPO_MODALIDAD			CHAR(1)
);



